service: orders-service

frameworkVersion: ">=2.53.1"
configValidationMode: error
variablesResolutionMode: 20210326
disabledDeprecations:
  - CLI_OPTIONS_SCHEMA

plugins:
  - serverless-python-requirements
  - serverless-iam-roles-per-function
  - serverless-appsync-plugin

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  timeout: 30
  memorySize: 512
  logRetentionInDays: 14
  versionFunctions: false
  stackName: ${self:custom.base_name}
  stage: ${self:custom.arguments.stage}
  region: ${self:custom.arguments.region}

custom:
  arguments: ${file( .local-arguments.yml )}
  base_name: ${self:custom.arguments.prefix}-${self:service}-${self:custom.arguments.region}
  dynamodb:
    orders:
      table_name: ${self:custom.arguments.prefix}-${self:custom.arguments.stage}-orders
  cognito:
    userpool:
      name: ${self:custom.arguments.prefix}-${self:custom.arguments.stage}-user-pool
    client:
      name: ${self:custom.arguments.prefix}-${self:custom.arguments.stage}-user-pool-client
  appSync:
    name: orders-api
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: ${self:provider.region}
      defaultAction: ALLOW
      userPoolId: {Ref: UserPool}
    mappingTemplates:
      - dataSource: createOrder
        type: Mutation
        field: createOrder
        request: false
        response: false
    dataSources:
      - type: AWS_LAMBDA
        name: createOrder
        config:
          functionName: CreateOrder
          iamRoleStatements:
            - Effect: "Allow"
              Action:
                - "lambda:invokeFunction"
              Resource:
                - "arn:aws:lambda:${aws:region}:${aws:accountId}:function:createOrder"
                - "arn:aws:lambda:${aws:region}:${aws:accountId}:function:createOrder:*"
  pythonRequirements:
    useStaticCache: true
    useDownloadCache: true
    cacheLocation: .env/requirements_cache
    pythonBin: /usr/bin/python3
    dockerizePip: non-linux
    layer:
      name: python-requirements
      description: Python requirements lambda layer
      compatibleRuntimes:
        - python3.8
      licenseInfo: GPLv3
      allowedAccounts:
        - "*"

package:
  individually: true
  patterns:
    - "!**/*"
    - src/controller/order.py
    - src/controller/repository.py
    - src/model/order.py
    - src/service/dynamodb.py
    - src/helper/boto.py
    - src/helper/exception.py
    - src/helper/model.py
    - src/helper/tools.py

functions:
  CreateOrder:
    name: createOrder
    handler: src/handler/create_order.handler
    environment:
      LOG_LEVEL: debug
      ORDERS_TABLE: ${self:custom.dynamodb.orders.table_name}
    iamRoleStatementsName: CreateOrderRole
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:GetItem
          - dynamodb:PutItem
        Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.dynamodb.orders.table_name}"
    package:
      patterns:
        - src/handler/create_order.py
    layers:
      - {Ref: PythonRequirementsLambdaLayer}

resources:
  - ${file( resources/infrastructure/cognito.yml )}
  - ${file( resources/infrastructure/dynamodb.yml )}
