---
Resources:
  OrdersDynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        -
          AttributeName: order_id
          AttributeType: S
      KeySchema:
        -
          AttributeName: order_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.dynamodb.orders.table_name}
