---
name: "Build check"
on:
  pull_request:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.FAKE_BUILD_KEY }}
          aws-secret-access-key: ${{ secrets.FAKE_BUILD_SECRET }}
          aws-region: eu-west-1
      - name: Try to build docker image
        run: docker build --build-arg access_key="$AWS_ACCESS_KEY_ID" --build-arg secret_key="$AWS_SECRET_ACCESS_KEY" --build-arg aws_region=eu-west-1 -t build-check:test .
