---
name: "Build and deploy check"
on:
  pull_request:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BUILD_KEY }}
          aws-secret-access-key: ${{ secrets.BUILD_SECRET }}
          aws-region: eu-west-1
      - name: Build image
        uses: neovasili/aws-codebuild@v1.1.1
        with:
          aws_region: eu-west-1
          codebuild_job_name: build-images
          codebuild_log_group: /aws/codebuild/build-images-project
          s3_path: ${{ secrets.ARTIFACTS_ACCOUNT }}-build-images-project-source-bucket/orders-backend
        env:
          PLAINTEXT_SOURCE_BUCKET_NAME: ${{ secrets.ARTIFACTS_ACCOUNT }}-build-images-project-source-bucket
          PLAINTEXT_AWS_ACCOUNT_ID: ${{ secrets.ARTIFACTS_ACCOUNT }}
          PLAINTEXT_IMAGE_REPO_NAME: orders-backend
          PLAINTEXT_IMAGE_TAG: ci_${{ github.sha }}

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BUILD_KEY }}
          aws-secret-access-key: ${{ secrets.BUILD_SECRET }}
          aws-region: eu-west-1
      - name: Deploy BackendStack check
        uses: neovasili/aws-codebuild@v1.1.1
        with:
          aws_region: eu-west-1
          codebuild_job_name: orders-backend-deploy
          codebuild_log_group: /aws/codebuild/orders-backend-deploy-project
          override_image_ssm_base: /codebuild/orders-backend-deploy/image-base
          override_image_tag_prefix: ci
        env:
          PLAINTEXT_AWS_ACCOUNT_ID: ${{ secrets.ARTIFACTS_ACCOUNT }}
          PLAINTEXT_STAGE: ci
          PLAINTEXT_REGION: eu-west-1
          PLAINTEXT_PREFIX: sgcc
          PLAINTEXT_API_VERSION: ci
      - name: Remove BackendStack temporally created stack
        if: ${{ always() }}
        uses: neovasili/aws-codebuild@v1.1.1
        with:
          aws_region: eu-west-1
          codebuild_job_name: orders-backend-destroy
          codebuild_log_group: /aws/codebuild/orders-backend-destroy-project
          override_image_ssm_base: /codebuild/orders-backend-destroy/image-base
          override_image_tag_prefix: ci
        env:
          PLAINTEXT_AWS_ACCOUNT_ID: ${{ secrets.ARTIFACTS_ACCOUNT }}
          PLAINTEXT_STAGE: ci
          PLAINTEXT_REGION: eu-west-1
          PLAINTEXT_PREFIX: sgcc
          PLAINTEXT_API_VERSION: ci
